'use client'

import { useEffect, useState } from 'react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { FileText, File, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth } from '@/lib/auth-context'
import { supabase, type Profile } from '@/lib/supabase'

interface ServiceRecord {
  id: string
  customerName: string
  contractName: string
  technicianName: string
  service_date: string
  status: string
  notes: string
  contractPrice: number | null
}

interface ExportModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  records: ServiceRecord[]
}

export function ExportModal({ open, onOpenChange, records }: ExportModalProps) {
  const { user } = useAuth()
  const [loading, setLoading] = useState(false)
  const [companyName, setCompanyName] = useState('')

  useEffect(() => {
    const loadProfile = async () => {
      if (!user?.id) return
      try {
        const { data } = await supabase
          .from('profiles')
          .select('company_name')
          .eq('id', user.id)
          .single()

        if (data) {
          setCompanyName((data as Profile).company_name || 'Service History Report')
        }
      } catch (error) {
        console.error('[v0] Error loading profile:', error)
      }
    }

    loadProfile()
  }, [user?.id])

  const generateCSV = () => {
    setLoading(true)
    try {
      const headers = ['Customer Name', 'Contract Name', 'Technician', 'Service Date', 'Price (Rs.)', 'Status', 'Notes']
      const csvContent = [
        headers.join(','),
        ...records.map(record =>
          [
            `"${record.customerName}"`,
            `"${record.contractName}"`,
            `"${record.technicianName}"`,
            `"=""${record.service_date}"""`,
            `"${record.contractPrice != null ? record.contractPrice : ''}"`,
            `"${record.status}"`,
            `"${(record.notes || '').replace(/"/g, '""')}"`,
          ].join(',')
        ),
      ].join('\n')

      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
      const link = document.createElement('a')
      const url = URL.createObjectURL(blob)
      const fileName = `service-history-${new Date().toISOString().split('T')[0]}.csv`

      link.setAttribute('href', url)
      link.setAttribute('download', fileName)
      link.style.visibility = 'hidden'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)

      toast.success('CSV exported successfully')
      onOpenChange(false)
    } catch (error) {
      console.error('[v0] Error generating CSV:', error)
      toast.error('Failed to export CSV')
    } finally {
      setLoading(false)
    }
  }

  const generatePDF = () => {
    setLoading(true)
    try {
      const exportDate = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
      const printWindow = window.open('', '_blank')
      if (!printWindow) {
        toast.error('Please allow popups to export PDF')
        return
      }
      const rows = records.map((record, i) => {
        const status = (record.status || '').toLowerCase()
        const statusColor = status === 'completed' ? '#16a34a' : status === 'pending' ? '#ca8a04' : status === 'cancelled' ? '#dc2626' : '#475569'
        return `<tr style="background:${i % 2 === 0 ? '#f0f9ff' : '#fff'}">
          <td>${record.customerName || '—'}</td>
          <td>${record.contractName || '—'}</td>
          <td>${record.technicianName || '—'}</td>
          <td>${record.service_date || '—'}</td>
          <td>${record.contractPrice != null ? 'Rs.' + Number(record.contractPrice).toLocaleString('en-IN') : '—'}</td>
          <td style="color:${statusColor};font-weight:bold">${record.status || '—'}</td>
          <td>${(record.notes || '—').replace(/</g, '&lt;')}</td>
        </tr>`
      }).join('')
      printWindow.document.write(`<!DOCTYPE html><html><head><title>Service History</title>
        <style>body{font-family:helvetica,sans-serif;margin:20px;color:#0f172a}
        h2{font-size:15px;margin:0}p{font-size:9px;color:#475569;margin:4px 0 12px}
        table{width:100%;border-collapse:collapse;font-size:9px}
        th{background:#162d3c;color:#fff;padding:5px 4px;text-align:left}
        td{padding:4px;border-bottom:1px solid #cbd5e1}
        footer{font-size:8px;color:#94a3b8;text-align:center;margin-top:20px}
        @media print{footer{position:fixed;bottom:0;width:100%}}</style></head>
        <body><h2>${companyName || 'Service History Report'}</h2>
        <p>Exported: ${exportDate} &nbsp;|&nbsp; Total Records: ${records.length}</p>
        <table><thead><tr><th>Customer Name</th><th>Contract</th><th>Technician</th><th>Date</th><th>Price (Rs.)</th><th>Status</th><th>Notes</th></tr></thead>
        <tbody>${rows}</tbody></table>
        <footer>Generated by Remindi · remindi.online</footer>
        <script>window.onload=function(){window.print();window.onafterprint=function(){window.close()}}</script>
        </body></html>`)
      printWindow.document.close()
      toast.success('PDF export opened — use Print > Save as PDF')
      onOpenChange(false)
    } catch (error) {
      console.error('[v0] Error generating PDF:', error)
      toast.error('Failed to export PDF')
    } finally {
      setLoading(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Export Service History</DialogTitle>
          <DialogDescription>
            Choose a format to export {records.length} service records
          </DialogDescription>
        </DialogHeader>
        <div className="flex flex-col gap-3 py-4">
          <Button
            onClick={generateCSV}
            disabled={loading || records.length === 0}
            className="h-12 justify-start gap-3"
            variant="outline"
          >
            <FileText className="size-5" />
            <div className="flex flex-col items-start">
              <span className="font-medium">Export as CSV</span>
              <span className="text-xs text-muted-foreground">Excel compatible format</span>
            </div>
            {loading && <Loader2 className="ml-auto size-4 animate-spin" />}
          </Button>
          <Button
            onClick={generatePDF}
            disabled={loading || records.length === 0}
            className="h-12 justify-start gap-3"
            variant="outline"
          >
            <File className="size-5" />
            <div className="flex flex-col items-start">
              <span className="font-medium">Export as PDF</span>
              <span className="text-xs text-muted-foreground">Professional format with formatting</span>
            </div>
            {loading && <Loader2 className="ml-auto size-4 animate-spin" />}
          </Button>
        </div>
        <div className="flex justify-end">
          <Button
            variant="ghost"
            onClick={() => onOpenChange(false)}
            disabled={loading}
          >
            Cancel
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
